### ISSUE TITLE
Bugged gamelist importing

### ISSUE THREAD

**Issue by Talref** [bnovakovic/GameList_Converter#5]
As you can see I've proper directory structure and gamelists are present:

```
 find . -type f -name "gamelist.xml"
./3do/gamelist.xml
./adam/gamelist.xml
./advision/gamelist.xml
./amiga1200/gamelist.xml
./amiga500/gamelist.xml
./amstradcpc/gamelist.xml
...
```

console reports:

```
Game list loaded. Unable to convert 128 files
Game list loaded. Unable to convert 128 files
```

<img width="632" height="258" alt="Image" src="https://github.com/user-attachments/assets/754c2e92-0363-4799-8eb2-a349fb4906fd" />

This is the only output I have.

These gamelists are originally made for EmulationStation (Batocera & Retrobat) but they work flawlessly (media and all) with Retropie.

**Comment by BojanNovakovic-TomTom** [comment]
Hello @Talref , thanks for reporting this. Any way you can provide me with couple of these XML files (preferably all of them), so that I can test locally, check what's going on, and fix the issue?

Also, is any system recognized? What happens when you click on Select system?

Thanks.

**Comment by bnovakovic** [comment]
Hello @Talref, thanks for reporting this. Any way you can provide me with couple of these XML files (preferably all of them), so that I can test locally, check what's going on, and fix the issue?

Also, is any system recognized? What happens when you click on Select system?

One more thing, unfortunately those stations have different directory naming. If you can provide that too, I would appreciate it. I have Retrobat myself, but do not have Botaceara. I might kill two bugs here at once then :)

Thanks.

**Comment by Talref** [comment]
[gamelists.tar.gz](https://github.com/user-attachments/files/21711345/gamelists.tar.gz)
Should be all of them. 

No system is recognized. If I click Select System I have a list of 4 Unknown () like in the picture I've sent. It's recognizing these half life ports, the steam gamlist.xml (that contains only steam), a set of CRT calibration tools and a game demo that I don't recognize (but I have a ton of things there as you can see from the tar).

In the tar file there's the dir structure of my roms directory (and it works both in Batocera and Retrobat for what I can see, fringe systems aside).

Tell me if you need anything else.

**Comment by bnovakovic** [comment]
Thanks a lot. I've managed to reproduce locally. I will see to fix it soon.

**Comment by Talref** [comment]
I've found the problem(s).
1. Capitalization of "system" tag (in my xml files System was system). This is solved by forcing Jackson XML to ignore capitalization.
2. Some tags (like "database") aren't present in my xmls. This is solved by making all tags optional.

I've forked the repo and now it works on my part:

<img width="1273" height="701" alt="Image" src="https://github.com/user-attachments/assets/3cefd760-d8b6-42d8-bfcd-9805f382a420" />

I still have trouble with cores recognition (retroarch/cores is hardcoded but, for example, under linux cores installed from the frontend are in ./libretro). I'll try to see into it now.

**Comment by Talref** [comment]
Fixed the paths for cores/info for the most common paths used in linux and fixed the executable (was using retroarch/retroarch.sh by default but many distros install retroarch in /usr).
I can't test Windows because I don't have a windows machine here.
I can make a pull request if you accept one.

**Comment by bnovakovic** [comment]
Hey, thanks. You can make a PR. I already fixed some things also, and I see we did it in a similar way. You can make a PR, and either I will append on it (if I do not accept it), or maybe suggest changes. 
I have Windows and MacOS machines to test.

**Comment by bnovakovic** [comment]
You can see changes [here](https://github.com/bnovakovic/GameList_Converter/commit/94291fd84532a4c703c913b5727a91ad6333248e). Pull my main to get the latest ones. This does not fix everything yet. I will address these in couple of hours.

**Comment by Talref** [comment]
Last pull imports but can't find the cores, and console is full of date parsing errors like this:

```
java.time.format.DateTimeParseException: Text '2024' could not be parsed at index 4
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2108)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2010)
        at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
        at screens.gamelistscreen.mappers.GameDataToUiModelKt.convertToReadableDate(GameDataToUiModel.kt:48)
        at screens.gamelistscreen.mappers.GameDataToUiModelKt.toGameInfoUiModel(GameDataToUiModel.kt:27)
        at screens.gamelistscreen.mappers.GameDataToUiModelKt.toGameSystemUiModel(GameDataToUiModel.kt:17)
        at screens.export.retroarch.ExportRetroArchScreenViewModel$2$1.emit(ExportRetroArchScreenViewModel.kt:98)
        at screens.export.retroarch.ExportRetroArchScreenViewModel$2$1.emit(ExportRetroArchScreenViewModel.kt:94)
        at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:401)
        at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I'll make the PR.

**Comment by bnovakovic** [comment]
Hey, I pushed most of the fixes. Also added support for new systems. Can you please test it out and let me know? As for additional dirs for Retroarch, I will have to do it separately.

**Comment by Talref** [comment]
Gamelists import fine but cores aren't detected if I choose my retroarch directory.

They are listed in the export section if I select retroarch/libretro (and I think this works because cores info files are in retroarch/libretro/info on my part and your logic was searching for a ./info directory) but export function is broken (the list of cores is loaded but core is flagged as uninstalled/undetected).

Did you try to pull the libretro path from the cfg file? I don't have time to read your changes now.

**Comment by bnovakovic** [comment]
Ahhh, I see what you mean. I can load retroarch.cfg, and read all the paths I need. OK, got it. I will handle it like that and let you know. Thanks!

**Comment by bnovakovic** [comment]
OK, I think I resolved issues with non local paths of cores and info. Here is how it works now. 
it reads retroarch.cfg, and this is how it parses it. 
Local paths start with `:`, at least on Windows.
Logic is like this:
if null in settings use old method to _hardcode_ subdir
if (starts.with :) append to retroarch path and add that local dir. 
if (anything else) just use that path

if (libretro_info_path = ":\info123") path would be retroArchDir\info123
if (libretro_info_path = ~/home/retroarchinfo) path would be ~/home/retroarchinfo
if (no_settings) retroarchInfo/info

Same goes for liberto path. 

I did not still fix executable path. I will have to see a proper way of doing it. Maybe in some future version. But in the meantime, can you please try latest main and tell me if I at least fixed cores and info paths for you. 

Thanks a lot for your help so far.

**Comment by Talref** [comment]
Cores recognition and export work now, good job!

A suggestion for the logic to find the exec:

If windows you go retrobat.exe like usual
If linux you check "which retroarch" (sys command): if it's installed from repos you'll get a path, if you get not found then retroarch is almost surely portable (so ./retroarch.sh). Since linux paths start with `/` you can use the same method you've used for the cores path to discern from the two.
I have no idea how mac handles it.

Anyway, even if you don't want to implement it now at least implement a basic error handling since the app crashes hard with no log on console on "test game".

Thank you for taking your time to write a software that's useful!

**Comment by bnovakovic** [comment]
I'm happy to see that it works for you.

Can you please give me output of `which retroarch`? I don't have Linux, and wanna be sure I'm doing it right.

**Comment by Talref** [comment]
Of course:

```
> which retroarch
/usr/bin/retroarch
```

This should be ok even with flatpak or snap installations (I can't test that now though)

**Comment by bnovakovic** [comment]
Hey @Talref , sorry for delay. I was unable to work for some days. I did as you suggested in my latest commit. But I kinda doubt it would work. Since your command does not return path with full .so executable. Should I append executable and use then  `/usr/bin/retroarch/retroarch.so` as full executable path?
I tested on Windows, and which retroarch would returen full path with executable. 

As for error handling, can you give me logcat output? I've added not to allow execution if executable is not found. But I am not sure it would work in your case.

**Comment by bnovakovic** [comment]
I added logic to append executable if executable is not directly in the path. because someone can add `/usr/bin/retroarch/retroarch.so` int their path. So it should be covered now.

**Comment by Talref** [comment]
> your command does not return path with full .so executable.

That's normal. Linux doesn't have an executable extension like windows has. Ability to execute files is enabled via file permissions ( `chmod +x filename` )

More so, if `which retroarch` is returning a valid filepath that means it can be run from everywhere (that's the purpose of having it inside the paths) so you can just run retroarch with your arguments, leaving the path out of it, if which succeeds. 

> As for error handling, can you give me logcat output? I've added not to allow execution if executable is not found. But I am not sure it would work in your case.

Logcat is an Android utility and doesn't apply to desktop linux distros. I've tried your last commit (I'm using ./gradlew run) and the program just hangs on
```
> :composeApp:run
```
forcing me to stop it from terminal.

You already have logic to disable "Test Game" if cores aren't found if I'm not mistaken. Just add a successful which check to it if the program runs on linux (and there's no retroarch.sh in the selected directory) and you should be ok with the majority of use cases. 

> I added logic to append executable if executable is not directly in the path. because someone can add `/usr/bin/retroarch/retroarch.so` int their path. So it should be covered now.

You can't (and shouldn't) add an executable in your path. PATH is an environment variable that contains a list of... paths, not executables. 
If I run
```
anything
```
in a terminal the terminal will try to run an executable with that name, first in the current path and then if there's none it will try in all the paths declared in PATH.
You can print in a console the values of PATH 

Linux:
```
echo $PATH
```
Win:
```
echo %PATH%
```
Win Powershell:
```
echo $Env:Path
```

Even in Windows, if you print PATH you'll see that it contains paths, not executables directly. 

EDIT:
So, basically: You shouldn't need to add any path nor extension if `which retroarch` returns a valid path. And usually on linux `which retroarch` **will** return a valid path since it's usually installed from a repository. 

Snap packages (Ubuntu, mainly) use instead a /snap/bin path and should be ok with which command.

The exception to it are Flatpak installs and .appimage files. These are **meant** to be sandboxes and isolated from the system, for simplicity and security. Adding a flatpak (or, worse, AppImage) functionality to your program would be a headache, IMO, and an user that chooses to use flatpaks and appimages should know that they're giving up customization for ease of use so I won't even try that route.

Another fringe example could be a self-compiled retroarch instance, but then again it's not the target of such an utility app.

**Comment by bnovakovic** [comment]
Hey, thanks a lot for this feedback. I think I know what to do to make it work properly. 

> Logcat is an Android utility and doesn't apply to desktop linux distros. I've tried your last commit (I'm using ./gradlew run) and the program just hangs on

Wait, so it does not work at all now for you? You cannot use converter at all, or behaviour above happens only when you want to test the game? If it always hangs, please go to [ExportRetroArchScreenViewModel.kt#81](https://github.com/bnovakovic/GameList_Converter/blob/main/composeApp/src/commonMain/kotlin/screens/export/retroarch/ExportRetroArchScreenViewModel.kt#L81C18-L81C45) and comment out `setRetroArchExecutablePath()`. Then try again and tell me if it works properly.

**Comment by Talref** [comment]
> Wait, so it does not work at all now for you? You cannot use converter at all, or behaviour above happens only when you want to test the game?

Sorry, I pasted just the last line in a hurry. Proper error in log is:

```
Executing command [which, retroarch]
Executing command [/usr/bin/retroarchretroarch.sh, -L, /home/eradan/.config/retroarch/libretro/virtualjaguar_libretro.so, /home/eradan/vault/emulation/roms/jaguar/Raiden (World) (Rev A).j64]
java.io.IOException: Cannot run program "/usr/bin/retroarchretroarch.sh": error=2, No such file or directory
```

You can tell from `/usr/bin/retroarchretroarch.sh` that you're still trying to append "retroarch.sh" to the command.
My advice is to scrap the pathing completely and if `which` is successful (if it returns a string that starts with a /, for example) then just run `retroarch`, with no path and no extension. You **can** hardcode `retroarch` in this case, because a successful `which` tells us that there is a system wide `retroarch` command available.

**Comment by bnovakovic** [comment]
Aha OK, that makes sense. I know what to do. I will do it later today But it is highly important that I know that whole app does not hang for you when you start it? You can still export and create playlists, right?

**Comment by bnovakovic** [comment]
BTW. if you run the app using play button (with desktop configuration on dropdown beside run button), you should have full crash logs after app is crashed no matter if android or desktop.

**Comment by Talref** [comment]
> Aha OK, that makes sense. I know what to do. I will do it later today But it is highly important that I know that whole app does not hang for you when you start it? You can still export and create playlists, right?

Yes, that works.

**Comment by bnovakovic** [comment]
> Yes, that works.
Phew, I got scared whole app is hanging :D. 

OK, I implemented the change you suggested. Can you test please. All should work now. Also I did some exception handling on command execution, so app should not longer crash if executable is bad. We do not allow test if executable is not found.

**Comment by Talref** [comment]
Both fixes work and I can't replicate the crash anymore. 
Nice job!
I think you can close this one. I can open another if I find other bugs. Thanks for your work.

**Comment by bnovakovic** [comment]
I am super happy to hear that. I cannot tank you enough for helping me with this. Thanks a lot! If you have any issues, please feel free to rais the bugs, and thanks again for sticking with me until we had this one resolved.
